#!/bin/bash

FILES=$(git ls -p debugger)
if [[ -n "$FILES" ]]; then
    echo "$(tput setaf 1)[ERROR]$(tput sgr0) You have left a debugger statement in the following files:"
    echo "$FILES"
    exit 1
fi

