#!/bin/bash
# https://osdir.com/ml/git/2009-01/msg00298.html

STR=$(git config --get-all hooks.pre-commit.hook)

for HOOK in $STR; do
    sh "./.git/hooks/pre-commit.d/$HOOK"

    if [ "$?" -eq 1 ]; then
        exit 1
    else
        # Separate the hooks by an empty line.
        echo
    fi

done

